# coding=utf-8
import time

from selenium.webdriver.common.by import By

from service.bpm_service.common_funcation import choice_menu, start_add, enter_apartment, choice_path, submit, agree, \
    invalid, delete_bill, cancel, refuse, RIsubmit
from service.bpm_service.pay import choice_budget, edit_matter, choice_RI, start_NORI, edit_money1, edit_matter1, \
    pay_setting, write_off


def budget_up(driver):
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算追加发起、通过、作废、删除')
    submit(driver)
    agree(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    invalid(driver)
    driver.refresh()
    delete_bill(driver)


def budget_up1(driver):     # 撤销复制单据
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算追加发起、撤销')
    submit(driver)
    cancel(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//button[text()='复制单据']").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    edit_matter(driver, '、复制单据、通过')
    submit(driver)
    agree(driver)


def budget_up2(driver):     # 撤销删除
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算追加发起、撤销、删除')
    submit(driver)
    cancel(driver)
    time.sleep(0.5)
    delete_bill(driver)


def budget_up3(driver):     # 驳回删除
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算追加发起、驳回、删除')
    submit(driver)
    time.sleep(0.5)
    refuse(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    delete_bill(driver)


def budget_down(driver):
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算调减']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算调减发起、通过、作废、删除')
    submit(driver)
    agree(driver)
    time.sleep(0.5)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    invalid(driver)
    driver.refresh()
    delete_bill(driver)


def budget_down1(driver):     # 撤销复制单据
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算调减发起、撤销')
    submit(driver)
    cancel(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//button[text()='复制单据']").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    edit_matter(driver, '、复制单据、通过')
    submit(driver)
    agree(driver)


def budget_down2(driver):     # 撤销删除
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算调减发起、撤销、删除')
    submit(driver)
    cancel(driver)
    time.sleep(0.5)
    delete_bill(driver)


def budget_down3(driver):     # 驳回删除
    choice_menu(driver, '预算管理', '调整申请')
    start_add(driver, '+ 发起预算调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='预算追加']").click()
    choice_budget(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整预算金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '预算调减发起、驳回、删除')
    submit(driver)
    refuse(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    delete_bill(driver)


def budget_ri_down(driver):     # 调整
    choice_menu(driver, '支出管理', '报销申请')
    start_NORI(driver)
    choice_budget(driver)
    edit_money1(driver, '500')
    enter_apartment(driver)
    choice_path(driver, '报销申请单自审')
    driver.find_element(By.XPATH, "//input[@id='attachmentNumber']").send_keys(5)
    edit_matter1(driver, '核销调减使用')
    pay_setting(driver)
    RIsubmit(driver)
    agree(driver)
    write_off(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(3)
    start_add(driver, '+ 发起核销金额调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='核销金额调减']").click()
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//div[@id='globalLayoutContent']/div/div/div[3]/div[3]/div/div["
                                  "2]/div/div/div/div/div[1]/div[2]/table/tbody/tr[1]").click()
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整已核销金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '核销调减发起、通过、作废、删除')
    submit(driver)
    agree(driver)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    invalid(driver)
    driver.refresh()
    delete_bill(driver)


def budget_ri_down1(driver):
    choice_menu(driver, '支出管理', '报销申请')
    start_NORI(driver)
    choice_budget(driver)
    edit_money1(driver, '500')
    enter_apartment(driver)
    choice_path(driver, '报销申请单自审')
    driver.find_element(By.XPATH, "//input[@id='attachmentNumber']").send_keys(5)
    edit_matter1(driver, '核销调减使用')
    pay_setting(driver)
    RIsubmit(driver)
    agree(driver)
    write_off(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(3)
    start_add(driver, '+ 发起核销金额调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='核销金额调减']").click()
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//div[@id='globalLayoutContent']/div/div/div[3]/div[3]/div/div["
                                  "2]/div/div/div/div/div[1]/div[2]/table/tbody/tr[1]").click()
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整已核销金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '核销调减发起、撤销')
    submit(driver)
    cancel(driver)
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//button[text()='复制单据']").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    edit_matter(driver, '、复制单据、通过')
    submit(driver)
    agree(driver)


def budget_ri_down2(driver):
    choice_menu(driver, '支出管理', '报销申请')
    start_NORI(driver)
    choice_budget(driver)
    edit_money1(driver, '500')
    enter_apartment(driver)
    choice_path(driver, '报销申请单自审')
    driver.find_element(By.XPATH, "//input[@id='attachmentNumber']").send_keys(5)
    edit_matter1(driver, '核销调减使用')
    pay_setting(driver)
    RIsubmit(driver)
    agree(driver)
    write_off(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(3)
    start_add(driver, '+ 发起核销金额调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='核销金额调减']").click()
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//div[@id='globalLayoutContent']/div/div/div[3]/div[3]/div/div["
                                  "2]/div/div/div/div/div[1]/div[2]/table/tbody/tr[1]").click()
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整已核销金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '核销调减发起、撤销')
    submit(driver)
    cancel(driver)
    delete_bill(driver)


def budget_ri_down3(driver):
    choice_menu(driver, '支出管理', '报销申请')
    start_NORI(driver)
    choice_budget(driver)
    edit_money1(driver, '500')
    enter_apartment(driver)
    choice_path(driver, '报销申请单自审')
    driver.find_element(By.XPATH, "//input[@id='attachmentNumber']").send_keys(5)
    edit_matter1(driver, '核销调减使用')
    pay_setting(driver)
    RIsubmit(driver)
    agree(driver)
    write_off(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(3)
    start_add(driver, '+ 发起核销金额调整 ')
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//li[text()='核销金额调减']").click()
    time.sleep(0.5)
    driver.find_element(By.XPATH, "//div[@id='globalLayoutContent']/div/div/div[3]/div[3]/div/div["
                                  "2]/div/div/div/div/div[1]/div[2]/table/tbody/tr[1]").click()
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    time.sleep(0.1)
    driver.find_element(By.XPATH, "//input[@placeholder='请输入调整已核销金额']").send_keys('100')
    driver.find_element(By.XPATH, "//span[text()='下一步']/..").click()
    enter_apartment(driver)
    choice_path(driver, '预算调整单自审')
    edit_matter(driver, '核销调减发起、驳回、删除')
    submit(driver)
    refuse(driver)
    time.sleep(0.5)
    choice_menu(driver, '预算管理', '调整申请')
    time.sleep(1)
    driver.find_element(By.XPATH, "//div[@class='ant-table-body']/table/tbody/tr[1]/td[1]/div").click()
    time.sleep(0.5)
    delete_bill(driver)